/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *frontpage;
    QToolButton *toolButton;
    QToolButton *toolButton_2;
    QPushButton *pushButton;
    QWidget *Aioage;
    QToolButton *toolButton_3;
    QToolButton *toolButton_4;
    QPushButton *pushButton_2;
    QWidget *customerpage;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QWidget *registerpage;
    QGroupBox *groupBox;
    QToolButton *toolButton_5;
    QLineEdit *lineEdit;
    QToolButton *toolButton_6;
    QToolButton *toolButton_7;
    QToolButton *toolButton_8;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QPushButton *pushButton_10;
    QWidget *lognpage;
    QGroupBox *groupBox_2;
    QToolButton *toolButton_9;
    QToolButton *toolButton_10;
    QToolButton *toolButton_11;
    QPushButton *pushButton_11;
    QToolButton *toolButton_12;
    QToolButton *toolButton_13;
    QToolButton *toolButton_14;
    QWidget *loginerporpage;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QWidget *congratspage;
    QToolButton *toolButton_15;
    QPushButton *pushButton_18;
    QWidget *chartpage;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QWidget *depositepage;
    QGroupBox *groupBox_4;
    QToolButton *toolButton_16;
    QToolButton *toolButton_17;
    QToolButton *toolButton_18;
    QToolButton *toolButton_19;
    QToolButton *toolButton_20;
    QToolButton *toolButton_21;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QWidget *takatulbopage;
    QGroupBox *groupBox_5;
    QToolButton *toolButton_22;
    QToolButton *toolButton_23;
    QToolButton *toolButton_24;
    QToolButton *toolButton_25;
    QToolButton *toolButton_26;
    QToolButton *toolButton_27;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QWidget *loanpage;
    QGroupBox *groupBox_6;
    QToolButton *toolButton_28;
    QToolButton *toolButton_29;
    QToolButton *toolButton_30;
    QPushButton *pushButton_23;
    QWidget *Loanfrom;
    QGroupBox *groupBox_7;
    QToolButton *toolButton_31;
    QToolButton *toolButton_32;
    QToolButton *toolButton_33;
    QToolButton *toolButton_34;
    QToolButton *toolButton_35;
    QToolButton *toolButton_36;
    QPushButton *pushButton_24;
    QWidget *loancongrats;
    QToolButton *toolButton_37;
    QPushButton *pushButton_25;
    QWidget *fdr1stpage;
    QToolButton *toolButton_38;
    QPushButton *pushButton_26;
    QWidget *fdrerammountpage;
    QGroupBox *groupBox_8;
    QToolButton *toolButton_39;
    QToolButton *toolButton_40;
    QPushButton *pushButton_27;
    QWidget *paybill1stpage;
    QGroupBox *groupBox_9;
    QToolButton *toolButton_41;
    QToolButton *toolButton_42;
    QToolButton *toolButton_43;
    QToolButton *toolButton_44;
    QPushButton *pushButton_28;
    QWidget *outh1st;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QWidget *outh2nd;
    QGroupBox *groupBox_10;
    QToolButton *toolButton_45;
    QToolButton *toolButton_46;
    QToolButton *toolButton_47;
    QToolButton *toolButton_48;
    QWidget *page;
    QToolButton *toolButton_49;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 800, 600));
        stackedWidget->setStyleSheet(QString::fromUtf8(""));
        frontpage = new QWidget();
        frontpage->setObjectName(QString::fromUtf8("frontpage"));
        toolButton = new QToolButton(frontpage);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(100, 50, 511, 27));
        toolButton_2 = new QToolButton(frontpage);
        toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
        toolButton_2->setGeometry(QRect(400, 80, 211, 27));
        pushButton = new QPushButton(frontpage);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(540, 500, 83, 29));
        stackedWidget->addWidget(frontpage);
        Aioage = new QWidget();
        Aioage->setObjectName(QString::fromUtf8("Aioage"));
        toolButton_3 = new QToolButton(Aioage);
        toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
        toolButton_3->setGeometry(QRect(270, 100, 151, 27));
        toolButton_4 = new QToolButton(Aioage);
        toolButton_4->setObjectName(QString::fromUtf8("toolButton_4"));
        toolButton_4->setGeometry(QRect(40, 180, 651, 27));
        pushButton_2 = new QPushButton(Aioage);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(560, 480, 83, 29));
        stackedWidget->addWidget(Aioage);
        customerpage = new QWidget();
        customerpage->setObjectName(QString::fromUtf8("customerpage"));
        pushButton_8 = new QPushButton(customerpage);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(220, 90, 281, 29));
        pushButton_9 = new QPushButton(customerpage);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(220, 120, 281, 29));
        stackedWidget->addWidget(customerpage);
        registerpage = new QWidget();
        registerpage->setObjectName(QString::fromUtf8("registerpage"));
        groupBox = new QGroupBox(registerpage);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(210, 50, 351, 511));
        toolButton_5 = new QToolButton(groupBox);
        toolButton_5->setObjectName(QString::fromUtf8("toolButton_5"));
        toolButton_5->setGeometry(QRect(20, 50, 91, 27));
        lineEdit = new QLineEdit(groupBox);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(120, 50, 191, 28));
        toolButton_6 = new QToolButton(groupBox);
        toolButton_6->setObjectName(QString::fromUtf8("toolButton_6"));
        toolButton_6->setGeometry(QRect(20, 100, 91, 27));
        toolButton_7 = new QToolButton(groupBox);
        toolButton_7->setObjectName(QString::fromUtf8("toolButton_7"));
        toolButton_7->setGeometry(QRect(20, 150, 101, 27));
        toolButton_8 = new QToolButton(groupBox);
        toolButton_8->setObjectName(QString::fromUtf8("toolButton_8"));
        toolButton_8->setGeometry(QRect(20, 200, 101, 27));
        lineEdit_2 = new QLineEdit(groupBox);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(120, 100, 191, 28));
        lineEdit_3 = new QLineEdit(groupBox);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(130, 150, 191, 28));
        lineEdit_4 = new QLineEdit(groupBox);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(130, 200, 191, 28));
        pushButton_10 = new QPushButton(groupBox);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(140, 250, 83, 29));
        stackedWidget->addWidget(registerpage);
        lognpage = new QWidget();
        lognpage->setObjectName(QString::fromUtf8("lognpage"));
        groupBox_2 = new QGroupBox(lognpage);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(260, 60, 371, 471));
        toolButton_9 = new QToolButton(groupBox_2);
        toolButton_9->setObjectName(QString::fromUtf8("toolButton_9"));
        toolButton_9->setGeometry(QRect(20, 60, 101, 27));
        toolButton_10 = new QToolButton(groupBox_2);
        toolButton_10->setObjectName(QString::fromUtf8("toolButton_10"));
        toolButton_10->setGeometry(QRect(20, 90, 101, 27));
        toolButton_11 = new QToolButton(groupBox_2);
        toolButton_11->setObjectName(QString::fromUtf8("toolButton_11"));
        toolButton_11->setGeometry(QRect(20, 120, 101, 27));
        pushButton_11 = new QPushButton(groupBox_2);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(110, 180, 83, 29));
        toolButton_12 = new QToolButton(groupBox_2);
        toolButton_12->setObjectName(QString::fromUtf8("toolButton_12"));
        toolButton_12->setGeometry(QRect(130, 60, 191, 27));
        toolButton_13 = new QToolButton(groupBox_2);
        toolButton_13->setObjectName(QString::fromUtf8("toolButton_13"));
        toolButton_13->setGeometry(QRect(130, 90, 191, 27));
        toolButton_14 = new QToolButton(groupBox_2);
        toolButton_14->setObjectName(QString::fromUtf8("toolButton_14"));
        toolButton_14->setGeometry(QRect(130, 120, 191, 27));
        stackedWidget->addWidget(lognpage);
        loginerporpage = new QWidget();
        loginerporpage->setObjectName(QString::fromUtf8("loginerporpage"));
        groupBox_3 = new QGroupBox(loginerporpage);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(170, 100, 441, 391));
        pushButton_12 = new QPushButton(groupBox_3);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(20, 40, 141, 29));
        pushButton_13 = new QPushButton(groupBox_3);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(20, 80, 141, 29));
        pushButton_14 = new QPushButton(groupBox_3);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(20, 120, 131, 29));
        pushButton_15 = new QPushButton(groupBox_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(20, 160, 141, 29));
        pushButton_16 = new QPushButton(groupBox_3);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(20, 200, 131, 29));
        pushButton_17 = new QPushButton(groupBox_3);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(20, 240, 131, 29));
        stackedWidget->addWidget(loginerporpage);
        congratspage = new QWidget();
        congratspage->setObjectName(QString::fromUtf8("congratspage"));
        toolButton_15 = new QToolButton(congratspage);
        toolButton_15->setObjectName(QString::fromUtf8("toolButton_15"));
        toolButton_15->setGeometry(QRect(80, 170, 551, 27));
        pushButton_18 = new QPushButton(congratspage);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(600, 450, 83, 29));
        stackedWidget->addWidget(congratspage);
        chartpage = new QWidget();
        chartpage->setObjectName(QString::fromUtf8("chartpage"));
        pushButton_3 = new QPushButton(chartpage);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(300, 60, 221, 29));
        pushButton_4 = new QPushButton(chartpage);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(300, 90, 221, 29));
        pushButton_5 = new QPushButton(chartpage);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(300, 120, 221, 29));
        pushButton_6 = new QPushButton(chartpage);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(300, 150, 221, 29));
        pushButton_7 = new QPushButton(chartpage);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(300, 180, 221, 29));
        stackedWidget->addWidget(chartpage);
        depositepage = new QWidget();
        depositepage->setObjectName(QString::fromUtf8("depositepage"));
        groupBox_4 = new QGroupBox(depositepage);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(70, 130, 381, 301));
        toolButton_16 = new QToolButton(groupBox_4);
        toolButton_16->setObjectName(QString::fromUtf8("toolButton_16"));
        toolButton_16->setGeometry(QRect(10, 40, 131, 27));
        toolButton_17 = new QToolButton(groupBox_4);
        toolButton_17->setObjectName(QString::fromUtf8("toolButton_17"));
        toolButton_17->setGeometry(QRect(150, 40, 161, 27));
        toolButton_18 = new QToolButton(groupBox_4);
        toolButton_18->setObjectName(QString::fromUtf8("toolButton_18"));
        toolButton_18->setGeometry(QRect(10, 70, 131, 27));
        toolButton_19 = new QToolButton(groupBox_4);
        toolButton_19->setObjectName(QString::fromUtf8("toolButton_19"));
        toolButton_19->setGeometry(QRect(150, 70, 161, 31));
        toolButton_20 = new QToolButton(groupBox_4);
        toolButton_20->setObjectName(QString::fromUtf8("toolButton_20"));
        toolButton_20->setGeometry(QRect(10, 100, 131, 27));
        toolButton_21 = new QToolButton(groupBox_4);
        toolButton_21->setObjectName(QString::fromUtf8("toolButton_21"));
        toolButton_21->setGeometry(QRect(150, 100, 161, 27));
        pushButton_19 = new QPushButton(groupBox_4);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(110, 150, 83, 29));
        pushButton_20 = new QPushButton(groupBox_4);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(250, 270, 83, 29));
        stackedWidget->addWidget(depositepage);
        takatulbopage = new QWidget();
        takatulbopage->setObjectName(QString::fromUtf8("takatulbopage"));
        groupBox_5 = new QGroupBox(takatulbopage);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(40, 40, 531, 441));
        toolButton_22 = new QToolButton(groupBox_5);
        toolButton_22->setObjectName(QString::fromUtf8("toolButton_22"));
        toolButton_22->setGeometry(QRect(0, 30, 141, 27));
        toolButton_23 = new QToolButton(groupBox_5);
        toolButton_23->setObjectName(QString::fromUtf8("toolButton_23"));
        toolButton_23->setGeometry(QRect(180, 30, 131, 27));
        toolButton_24 = new QToolButton(groupBox_5);
        toolButton_24->setObjectName(QString::fromUtf8("toolButton_24"));
        toolButton_24->setGeometry(QRect(0, 70, 141, 27));
        toolButton_25 = new QToolButton(groupBox_5);
        toolButton_25->setObjectName(QString::fromUtf8("toolButton_25"));
        toolButton_25->setGeometry(QRect(180, 70, 131, 27));
        toolButton_26 = new QToolButton(groupBox_5);
        toolButton_26->setObjectName(QString::fromUtf8("toolButton_26"));
        toolButton_26->setGeometry(QRect(0, 110, 141, 27));
        toolButton_27 = new QToolButton(groupBox_5);
        toolButton_27->setObjectName(QString::fromUtf8("toolButton_27"));
        toolButton_27->setGeometry(QRect(180, 110, 131, 27));
        pushButton_21 = new QPushButton(groupBox_5);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(130, 160, 83, 29));
        pushButton_22 = new QPushButton(groupBox_5);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(410, 390, 83, 29));
        stackedWidget->addWidget(takatulbopage);
        loanpage = new QWidget();
        loanpage->setObjectName(QString::fromUtf8("loanpage"));
        groupBox_6 = new QGroupBox(loanpage);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(100, 60, 611, 401));
        toolButton_28 = new QToolButton(groupBox_6);
        toolButton_28->setObjectName(QString::fromUtf8("toolButton_28"));
        toolButton_28->setGeometry(QRect(10, 50, 571, 27));
        toolButton_29 = new QToolButton(groupBox_6);
        toolButton_29->setObjectName(QString::fromUtf8("toolButton_29"));
        toolButton_29->setGeometry(QRect(10, 90, 571, 27));
        toolButton_30 = new QToolButton(groupBox_6);
        toolButton_30->setObjectName(QString::fromUtf8("toolButton_30"));
        toolButton_30->setGeometry(QRect(10, 130, 571, 27));
        pushButton_23 = new QPushButton(groupBox_6);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(260, 170, 83, 29));
        stackedWidget->addWidget(loanpage);
        Loanfrom = new QWidget();
        Loanfrom->setObjectName(QString::fromUtf8("Loanfrom"));
        groupBox_7 = new QGroupBox(Loanfrom);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(30, 80, 451, 421));
        toolButton_31 = new QToolButton(groupBox_7);
        toolButton_31->setObjectName(QString::fromUtf8("toolButton_31"));
        toolButton_31->setGeometry(QRect(50, 40, 181, 27));
        toolButton_32 = new QToolButton(groupBox_7);
        toolButton_32->setObjectName(QString::fromUtf8("toolButton_32"));
        toolButton_32->setGeometry(QRect(50, 70, 181, 27));
        toolButton_33 = new QToolButton(groupBox_7);
        toolButton_33->setObjectName(QString::fromUtf8("toolButton_33"));
        toolButton_33->setGeometry(QRect(50, 100, 181, 27));
        toolButton_34 = new QToolButton(groupBox_7);
        toolButton_34->setObjectName(QString::fromUtf8("toolButton_34"));
        toolButton_34->setGeometry(QRect(240, 40, 161, 27));
        toolButton_35 = new QToolButton(groupBox_7);
        toolButton_35->setObjectName(QString::fromUtf8("toolButton_35"));
        toolButton_35->setGeometry(QRect(240, 70, 161, 27));
        toolButton_36 = new QToolButton(groupBox_7);
        toolButton_36->setObjectName(QString::fromUtf8("toolButton_36"));
        toolButton_36->setGeometry(QRect(240, 100, 161, 27));
        pushButton_24 = new QPushButton(groupBox_7);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(310, 340, 83, 29));
        stackedWidget->addWidget(Loanfrom);
        loancongrats = new QWidget();
        loancongrats->setObjectName(QString::fromUtf8("loancongrats"));
        toolButton_37 = new QToolButton(loancongrats);
        toolButton_37->setObjectName(QString::fromUtf8("toolButton_37"));
        toolButton_37->setGeometry(QRect(10, 20, 741, 141));
        pushButton_25 = new QPushButton(loancongrats);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(630, 200, 83, 29));
        stackedWidget->addWidget(loancongrats);
        fdr1stpage = new QWidget();
        fdr1stpage->setObjectName(QString::fromUtf8("fdr1stpage"));
        toolButton_38 = new QToolButton(fdr1stpage);
        toolButton_38->setObjectName(QString::fromUtf8("toolButton_38"));
        toolButton_38->setGeometry(QRect(100, 60, 641, 181));
        pushButton_26 = new QPushButton(fdr1stpage);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(340, 280, 83, 29));
        stackedWidget->addWidget(fdr1stpage);
        fdrerammountpage = new QWidget();
        fdrerammountpage->setObjectName(QString::fromUtf8("fdrerammountpage"));
        groupBox_8 = new QGroupBox(fdrerammountpage);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(160, 30, 371, 341));
        toolButton_39 = new QToolButton(groupBox_8);
        toolButton_39->setObjectName(QString::fromUtf8("toolButton_39"));
        toolButton_39->setGeometry(QRect(10, 30, 131, 27));
        toolButton_40 = new QToolButton(groupBox_8);
        toolButton_40->setObjectName(QString::fromUtf8("toolButton_40"));
        toolButton_40->setGeometry(QRect(150, 30, 201, 27));
        pushButton_27 = new QPushButton(groupBox_8);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(100, 80, 83, 29));
        stackedWidget->addWidget(fdrerammountpage);
        paybill1stpage = new QWidget();
        paybill1stpage->setObjectName(QString::fromUtf8("paybill1stpage"));
        groupBox_9 = new QGroupBox(paybill1stpage);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(70, 90, 521, 311));
        toolButton_41 = new QToolButton(groupBox_9);
        toolButton_41->setObjectName(QString::fromUtf8("toolButton_41"));
        toolButton_41->setGeometry(QRect(0, 30, 231, 27));
        toolButton_42 = new QToolButton(groupBox_9);
        toolButton_42->setObjectName(QString::fromUtf8("toolButton_42"));
        toolButton_42->setGeometry(QRect(250, 30, 231, 27));
        toolButton_43 = new QToolButton(groupBox_9);
        toolButton_43->setObjectName(QString::fromUtf8("toolButton_43"));
        toolButton_43->setGeometry(QRect(0, 70, 231, 27));
        toolButton_44 = new QToolButton(groupBox_9);
        toolButton_44->setObjectName(QString::fromUtf8("toolButton_44"));
        toolButton_44->setGeometry(QRect(250, 70, 231, 27));
        pushButton_28 = new QPushButton(groupBox_9);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(390, 170, 83, 29));
        stackedWidget->addWidget(paybill1stpage);
        outh1st = new QWidget();
        outh1st->setObjectName(QString::fromUtf8("outh1st"));
        pushButton_29 = new QPushButton(outh1st);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(60, 60, 221, 29));
        pushButton_30 = new QPushButton(outh1st);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(60, 110, 221, 29));
        pushButton_31 = new QPushButton(outh1st);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(60, 160, 221, 29));
        stackedWidget->addWidget(outh1st);
        outh2nd = new QWidget();
        outh2nd->setObjectName(QString::fromUtf8("outh2nd"));
        groupBox_10 = new QGroupBox(outh2nd);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(50, 50, 461, 461));
        toolButton_45 = new QToolButton(groupBox_10);
        toolButton_45->setObjectName(QString::fromUtf8("toolButton_45"));
        toolButton_45->setGeometry(QRect(10, 30, 321, 41));
        toolButton_46 = new QToolButton(groupBox_10);
        toolButton_46->setObjectName(QString::fromUtf8("toolButton_46"));
        toolButton_46->setGeometry(QRect(80, 80, 201, 27));
        toolButton_47 = new QToolButton(groupBox_10);
        toolButton_47->setObjectName(QString::fromUtf8("toolButton_47"));
        toolButton_47->setGeometry(QRect(10, 120, 311, 51));
        toolButton_48 = new QToolButton(groupBox_10);
        toolButton_48->setObjectName(QString::fromUtf8("toolButton_48"));
        toolButton_48->setGeometry(QRect(80, 180, 191, 27));
        stackedWidget->addWidget(outh2nd);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        toolButton_49 = new QToolButton(page);
        toolButton_49->setObjectName(QString::fromUtf8("toolButton_49"));
        toolButton_49->setGeometry(QRect(20, 200, 751, 81));
        stackedWidget->addWidget(page);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 800, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        toolButton->setText(QApplication::translate("MainWindow", "Trust Bank", nullptr));
        toolButton_2->setText(QApplication::translate("MainWindow", "sequre your money", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "next", nullptr));
        toolButton_3->setText(QApplication::translate("MainWindow", "Aim", nullptr));
        toolButton_4->setText(QApplication::translate("MainWindow", "Our aim is to sequre money and to ", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Register", nullptr));
        pushButton_9->setText(QApplication::translate("MainWindow", "Sign in", nullptr));
        groupBox->setTitle(QString());
        toolButton_5->setText(QApplication::translate("MainWindow", "Name", nullptr));
        toolButton_6->setText(QApplication::translate("MainWindow", "Mail.", nullptr));
        toolButton_7->setText(QApplication::translate("MainWindow", "Phn. Number", nullptr));
        toolButton_8->setText(QApplication::translate("MainWindow", "Password", nullptr));
        pushButton_10->setText(QApplication::translate("MainWindow", "Register", nullptr));
        groupBox_2->setTitle(QString());
        toolButton_9->setText(QApplication::translate("MainWindow", "Name", nullptr));
        toolButton_10->setText(QApplication::translate("MainWindow", "Phn Number", nullptr));
        toolButton_11->setText(QApplication::translate("MainWindow", "Password", nullptr));
        pushButton_11->setText(QApplication::translate("MainWindow", "Log in", nullptr));
        toolButton_12->setText(QString());
        toolButton_13->setText(QString());
        toolButton_14->setText(QString());
        groupBox_3->setTitle(QString());
        pushButton_12->setText(QApplication::translate("MainWindow", "Deposite", nullptr));
        pushButton_13->setText(QApplication::translate("MainWindow", "Withdraw", nullptr));
        pushButton_14->setText(QApplication::translate("MainWindow", "About loan", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "Fixed deposite", nullptr));
        pushButton_16->setText(QApplication::translate("MainWindow", "Pay-bill", nullptr));
        pushButton_17->setText(QApplication::translate("MainWindow", "exit", nullptr));
        toolButton_15->setText(QApplication::translate("MainWindow", "Congrats!You have register your account successfully.Keep touch with us", nullptr));
        pushButton_18->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "Customer", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Authority", nullptr));
        pushButton_5->setText(QApplication::translate("MainWindow", "Bank Details", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Branches", nullptr));
        pushButton_7->setText(QApplication::translate("MainWindow", "Announcement", nullptr));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Deposite history", nullptr));
        toolButton_16->setText(QApplication::translate("MainWindow", "Current money", nullptr));
        toolButton_17->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_18->setText(QApplication::translate("MainWindow", "Deposite money", nullptr));
        toolButton_19->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_20->setText(QApplication::translate("MainWindow", "Total money", nullptr));
        toolButton_21->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "Confirm", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "Next", nullptr));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "GroupBox", nullptr));
        toolButton_22->setText(QApplication::translate("MainWindow", "Current Money", nullptr));
        toolButton_23->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_24->setText(QApplication::translate("MainWindow", "Withdraw Money", nullptr));
        toolButton_25->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_26->setText(QApplication::translate("MainWindow", "Now Current Money", nullptr));
        toolButton_27->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_21->setText(QApplication::translate("MainWindow", "Confrim", nullptr));
        pushButton_22->setText(QApplication::translate("MainWindow", "Next", nullptr));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Dear sir/madam.Assalamu alaikum!.", nullptr));
        toolButton_28->setText(QApplication::translate("MainWindow", "You can take loan from 10,000-200,000 with 3% interest rate", nullptr));
        toolButton_29->setText(QApplication::translate("MainWindow", "You can take loan from 200,001-500,000- with 5% interest rate", nullptr));
        toolButton_30->setText(QApplication::translate("MainWindow", "You can take loan from 500,001-700,000-- with 8% interest rate", nullptr));
        pushButton_23->setText(QApplication::translate("MainWindow", "I Agree", nullptr));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Loan form", nullptr));
        toolButton_31->setText(QApplication::translate("MainWindow", "Purpose", nullptr));
        toolButton_32->setText(QApplication::translate("MainWindow", "Enter ammount", nullptr));
        toolButton_33->setText(QApplication::translate("MainWindow", "How long will it take you", nullptr));
        toolButton_34->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_35->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_36->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_24->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_37->setText(QApplication::translate("MainWindow", "Congrats you have got the  loan successfully!!", nullptr));
        pushButton_25->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_38->setText(QApplication::translate("MainWindow", "You can take deposite for a cirtain time,we will give you 6.7% interest rate ", nullptr));
        pushButton_26->setText(QApplication::translate("MainWindow", "I agree", nullptr));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "deposite box", nullptr));
        toolButton_39->setText(QApplication::translate("MainWindow", "Enter Ammount", nullptr));
        toolButton_40->setText(QString());
        pushButton_27->setText(QApplication::translate("MainWindow", "Confrim", nullptr));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Pay Your Utilyty Bill", nullptr));
        toolButton_41->setText(QApplication::translate("MainWindow", "Enter 8 digit consumer number", nullptr));
        toolButton_42->setText(QApplication::translate("MainWindow", "...", nullptr));
        toolButton_43->setText(QApplication::translate("MainWindow", "Enter Ammount", nullptr));
        toolButton_44->setText(QApplication::translate("MainWindow", "...", nullptr));
        pushButton_28->setText(QApplication::translate("MainWindow", "Confirm", nullptr));
        pushButton_29->setText(QApplication::translate("MainWindow", "Managing Body", nullptr));
        pushButton_30->setText(QApplication::translate("MainWindow", "Bank Hostory", nullptr));
        pushButton_31->setText(QApplication::translate("MainWindow", "Yearly  Report", nullptr));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Managing Body", nullptr));
        toolButton_45->setText(QApplication::translate("MainWindow", "Managing director", nullptr));
        toolButton_46->setText(QApplication::translate("MainWindow", "MD.Mohiuddin ", nullptr));
        toolButton_47->setText(QApplication::translate("MainWindow", "Branch Manager", nullptr));
        toolButton_48->setText(QApplication::translate("MainWindow", "A.K.M. Afjal ", nullptr));
        toolButton_49->setText(QApplication::translate("MainWindow", "Trust  Bank was established on 31 December 1981. This was the first joint venture private bank in Bangladesh... ", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
