/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *Main_page;
    QToolButton *toolButton;
    QToolButton *toolButton_2;
    QPushButton *pushButton;
    QWidget *Aim_page;
    QToolButton *toolButton_3;
    QToolButton *toolButton_4;
    QPushButton *pushButton_2;
    QPushButton *pushButton_32;
    QWidget *Reg_Sing;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_33;
    QWidget *Reg_1st;
    QGroupBox *groupBox;
    QToolButton *toolButton_5;
    QLineEdit *name_box;
    QToolButton *toolButton_6;
    QToolButton *toolButton_7;
    QToolButton *toolButton_8;
    QLineEdit *mail_box;
    QLineEdit *phnnum_box;
    QLineEdit *pass_box;
    QPushButton *pushButton_10;
    QPushButton *pushButton_45;
    QWidget *Login;
    QGroupBox *groupBox_2;
    QToolButton *toolButton_9;
    QToolButton *toolButton_10;
    QToolButton *toolButton_11;
    QPushButton *pushButton_11;
    QPushButton *pushButton_46;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QWidget *Menu_2;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *education;
    QWidget *Reg_success;
    QToolButton *toolButton_15;
    QPushButton *pushButton_18;
    QWidget *Menue_1;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_47;
    QPushButton *pushButton_42;
    QWidget *Dep_Money;
    QGroupBox *groupBox_4;
    QToolButton *toolButton_16;
    QToolButton *toolButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_48;
    QLabel *label;
    QLineEdit *lineEdit_10;
    QToolButton *toolButton_12;
    QLineEdit *lineEdit;
    QWidget *With_Money;
    QGroupBox *groupBox_5;
    QToolButton *toolButton_22;
    QToolButton *toolButton_24;
    QPushButton *pushButton_21;
    QPushButton *pushButton_49;
    QLabel *label_3;
    QLineEdit *lineEdit_11;
    QPushButton *pushButton_60;
    QLineEdit *lineEdit_2;
    QWidget *Loan_1st;
    QGroupBox *groupBox_6;
    QToolButton *toolButton_28;
    QToolButton *toolButton_29;
    QToolButton *toolButton_30;
    QPushButton *pushButton_23;
    QPushButton *pushButton_50;
    QWidget *Loan_Form;
    QGroupBox *groupBox_7;
    QToolButton *toolButton_31;
    QToolButton *toolButton_32;
    QToolButton *toolButton_33;
    QPushButton *pushButton_24;
    QPushButton *pushButton_51;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QWidget *pagee12;
    QToolButton *toolButton_37;
    QPushButton *pushButton_25;
    QWidget *pagee13;
    QToolButton *toolButton_38;
    QPushButton *pushButton_26;
    QPushButton *pushButton_52;
    QWidget *Fdr;
    QGroupBox *groupBox_8;
    QToolButton *toolButton_39;
    QPushButton *pushButton_27;
    QPushButton *pushButton_53;
    QLineEdit *lineEdit_15;
    QWidget *pagee15;
    QToolButton *toolButton_50;
    QPushButton *pushButton_34;
    QWidget *Pay_Bill;
    QGroupBox *groupBox_9;
    QToolButton *toolButton_41;
    QToolButton *toolButton_43;
    QPushButton *Pay_Bill_2;
    QPushButton *pushButton_54;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QPushButton *pushButton_28;
    QLineEdit *lineEdit_3;
    QWidget *pagee17;
    QToolButton *toolButton_51;
    QPushButton *pushButton_35;
    QWidget *MBY;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_55;
    QWidget *pagee19;
    QGroupBox *groupBox_10;
    QToolButton *toolButton_45;
    QToolButton *toolButton_46;
    QToolButton *toolButton_47;
    QToolButton *toolButton_48;
    QPushButton *pushButton_56;
    QWidget *pageee20;
    QToolButton *toolButton_49;
    QToolButton *toolButton_52;
    QToolButton *toolButton_53;
    QPushButton *pushButton_36;
    QPushButton *pushButton_58;
    QWidget *Yearly_Report;
    QGroupBox *groupBox_11;
    QToolButton *toolButton_54;
    QToolButton *toolButton_55;
    QToolButton *toolButton_56;
    QToolButton *toolButton_57;
    QToolButton *toolButton_58;
    QToolButton *toolButton_59;
    QToolButton *toolButton_60;
    QToolButton *toolButton_61;
    QToolButton *toolButton_62;
    QToolButton *toolButton_63;
    QToolButton *toolButton_64;
    QPushButton *pushButton_37;
    QWidget *Bank_Details;
    QToolButton *toolButton_65;
    QToolButton *toolButton_66;
    QToolButton *toolButton_67;
    QToolButton *toolButton_68;
    QToolButton *toolButton_69;
    QPushButton *pushButton_38;
    QWidget *Branch;
    QToolButton *toolButton_70;
    QToolButton *toolButton_71;
    QPushButton *pushButton_39;
    QWidget *Announcement;
    QGroupBox *groupBox_14;
    QPushButton *pushButton_41;
    QPushButton *pushButton_59;
    QPushButton *pushButton_40;
    QWidget *Vacation;
    QGroupBox *groupBox_12;
    QToolButton *toolButton_73;
    QToolButton *toolButton_74;
    QToolButton *toolButton_75;
    QToolButton *toolButton_76;
    QToolButton *toolButton_77;
    QToolButton *toolButton_78;
    QToolButton *toolButton_79;
    QToolButton *toolButton_80;
    QToolButton *toolButton_81;
    QToolButton *toolButton_82;
    QToolButton *toolButton_83;
    QToolButton *toolButton_84;
    QToolButton *toolButton_85;
    QToolButton *toolButton_86;
    QToolButton *toolButton_87;
    QToolButton *toolButton_88;
    QToolButton *toolButton_89;
    QToolButton *toolButton_90;
    QToolButton *toolButton_91;
    QToolButton *toolButton_92;
    QToolButton *toolButton_93;
    QToolButton *toolButton_94;
    QToolButton *toolButton_95;
    QToolButton *toolButton_96;
    QToolButton *toolButton_97;
    QToolButton *toolButton_98;
    QToolButton *toolButton_99;
    QToolButton *toolButton_100;
    QToolButton *toolButton_101;
    QToolButton *toolButton_102;
    QToolButton *toolButton_103;
    QToolButton *toolButton_104;
    QPushButton *pushButton_43;
    QToolButton *toolButton_105;
    QWidget *Reqrutement_Notice;
    QGroupBox *groupBox_13;
    QToolButton *toolButton_106;
    QPushButton *pushButton_44;
    QWidget *pageee28;
    QToolButton *toolButton_107;
    QPushButton *pushButton_20;
    QWidget *pageee29;
    QLineEdit *lineEdit_8;
    QPushButton *pushButton_22;
    QWidget *pageee30;
    QLineEdit *lineEdit_9;
    QPushButton *pushButton_57;
    QWidget *page;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QPushButton *pushButton_61;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setStyleSheet(QString::fromUtf8("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
""));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(-60, 10, 800, 600));
        stackedWidget->setStyleSheet(QString::fromUtf8("Border:none;"));
        Main_page = new QWidget();
        Main_page->setObjectName(QString::fromUtf8("Main_page"));
        Main_page->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));"));
        toolButton = new QToolButton(Main_page);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(140, 50, 511, 27));
        toolButton_2 = new QToolButton(Main_page);
        toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
        toolButton_2->setGeometry(QRect(440, 90, 211, 27));
        pushButton = new QPushButton(Main_page);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(540, 500, 83, 29));
        stackedWidget->addWidget(Main_page);
        toolButton_2->raise();
        pushButton->raise();
        toolButton->raise();
        Aim_page = new QWidget();
        Aim_page->setObjectName(QString::fromUtf8("Aim_page"));
        Aim_page->setStyleSheet(QString::fromUtf8(""));
        toolButton_3 = new QToolButton(Aim_page);
        toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
        toolButton_3->setGeometry(QRect(310, 50, 151, 27));
        toolButton_3->setStyleSheet(QString::fromUtf8(""));
        toolButton_4 = new QToolButton(Aim_page);
        toolButton_4->setObjectName(QString::fromUtf8("toolButton_4"));
        toolButton_4->setGeometry(QRect(220, 90, 331, 61));
        pushButton_2 = new QPushButton(Aim_page);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(640, 320, 83, 29));
        pushButton_32 = new QPushButton(Aim_page);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(80, 320, 83, 29));
        stackedWidget->addWidget(Aim_page);
        Reg_Sing = new QWidget();
        Reg_Sing->setObjectName(QString::fromUtf8("Reg_Sing"));
        pushButton_8 = new QPushButton(Reg_Sing);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(280, 120, 281, 29));
        pushButton_9 = new QPushButton(Reg_Sing);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(280, 170, 281, 29));
        pushButton_33 = new QPushButton(Reg_Sing);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(110, 380, 83, 31));
        stackedWidget->addWidget(Reg_Sing);
        Reg_1st = new QWidget();
        Reg_1st->setObjectName(QString::fromUtf8("Reg_1st"));
        Reg_1st->setStyleSheet(QString::fromUtf8(""));
        groupBox = new QGroupBox(Reg_1st);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(230, 60, 351, 471));
        toolButton_5 = new QToolButton(groupBox);
        toolButton_5->setObjectName(QString::fromUtf8("toolButton_5"));
        toolButton_5->setGeometry(QRect(20, 50, 101, 27));
        name_box = new QLineEdit(groupBox);
        name_box->setObjectName(QString::fromUtf8("name_box"));
        name_box->setGeometry(QRect(130, 50, 191, 28));
        toolButton_6 = new QToolButton(groupBox);
        toolButton_6->setObjectName(QString::fromUtf8("toolButton_6"));
        toolButton_6->setGeometry(QRect(20, 100, 101, 27));
        toolButton_7 = new QToolButton(groupBox);
        toolButton_7->setObjectName(QString::fromUtf8("toolButton_7"));
        toolButton_7->setGeometry(QRect(20, 150, 101, 27));
        toolButton_8 = new QToolButton(groupBox);
        toolButton_8->setObjectName(QString::fromUtf8("toolButton_8"));
        toolButton_8->setGeometry(QRect(20, 200, 101, 27));
        mail_box = new QLineEdit(groupBox);
        mail_box->setObjectName(QString::fromUtf8("mail_box"));
        mail_box->setGeometry(QRect(130, 100, 191, 28));
        phnnum_box = new QLineEdit(groupBox);
        phnnum_box->setObjectName(QString::fromUtf8("phnnum_box"));
        phnnum_box->setGeometry(QRect(130, 150, 191, 28));
        pass_box = new QLineEdit(groupBox);
        pass_box->setObjectName(QString::fromUtf8("pass_box"));
        pass_box->setGeometry(QRect(130, 200, 191, 28));
        pushButton_10 = new QPushButton(groupBox);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(140, 250, 83, 29));
        pushButton_45 = new QPushButton(groupBox);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(10, 410, 83, 29));
        stackedWidget->addWidget(Reg_1st);
        Login = new QWidget();
        Login->setObjectName(QString::fromUtf8("Login"));
        groupBox_2 = new QGroupBox(Login);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(230, 50, 371, 471));
        toolButton_9 = new QToolButton(groupBox_2);
        toolButton_9->setObjectName(QString::fromUtf8("toolButton_9"));
        toolButton_9->setGeometry(QRect(20, 60, 101, 27));
        toolButton_10 = new QToolButton(groupBox_2);
        toolButton_10->setObjectName(QString::fromUtf8("toolButton_10"));
        toolButton_10->setGeometry(QRect(20, 90, 101, 27));
        toolButton_11 = new QToolButton(groupBox_2);
        toolButton_11->setObjectName(QString::fromUtf8("toolButton_11"));
        toolButton_11->setGeometry(QRect(20, 120, 101, 27));
        pushButton_11 = new QPushButton(groupBox_2);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(250, 160, 83, 29));
        pushButton_46 = new QPushButton(groupBox_2);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(30, 390, 83, 29));
        lineEdit_5 = new QLineEdit(groupBox_2);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(130, 60, 201, 28));
        lineEdit_6 = new QLineEdit(groupBox_2);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(130, 90, 201, 28));
        lineEdit_7 = new QLineEdit(groupBox_2);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(130, 120, 201, 28));
        stackedWidget->addWidget(Login);
        Menu_2 = new QWidget();
        Menu_2->setObjectName(QString::fromUtf8("Menu_2"));
        groupBox_3 = new QGroupBox(Menu_2);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(190, 120, 441, 391));
        groupBox_3->setStyleSheet(QString::fromUtf8("border:none;"));
        pushButton_12 = new QPushButton(groupBox_3);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(140, 30, 141, 31));
        pushButton_13 = new QPushButton(groupBox_3);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(140, 70, 141, 29));
        pushButton_14 = new QPushButton(groupBox_3);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(140, 150, 141, 29));
        pushButton_15 = new QPushButton(groupBox_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(140, 190, 141, 29));
        pushButton_16 = new QPushButton(groupBox_3);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(140, 110, 141, 29));
        pushButton_17 = new QPushButton(groupBox_3);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(140, 280, 141, 29));
        education = new QPushButton(groupBox_3);
        education->setObjectName(QString::fromUtf8("education"));
        education->setGeometry(QRect(140, 230, 141, 31));
        stackedWidget->addWidget(Menu_2);
        Reg_success = new QWidget();
        Reg_success->setObjectName(QString::fromUtf8("Reg_success"));
        toolButton_15 = new QToolButton(Reg_success);
        toolButton_15->setObjectName(QString::fromUtf8("toolButton_15"));
        toolButton_15->setGeometry(QRect(140, 190, 551, 27));
        pushButton_18 = new QPushButton(Reg_success);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(550, 440, 83, 29));
        stackedWidget->addWidget(Reg_success);
        Menue_1 = new QWidget();
        Menue_1->setObjectName(QString::fromUtf8("Menue_1"));
        pushButton_3 = new QPushButton(Menue_1);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(290, 60, 221, 29));
        pushButton_4 = new QPushButton(Menue_1);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(290, 100, 221, 29));
        pushButton_5 = new QPushButton(Menue_1);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(290, 150, 221, 29));
        pushButton_6 = new QPushButton(Menue_1);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(290, 200, 221, 29));
        pushButton_7 = new QPushButton(Menue_1);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(290, 250, 221, 29));
        pushButton_47 = new QPushButton(Menue_1);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(80, 450, 111, 29));
        pushButton_42 = new QPushButton(Menue_1);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(630, 450, 81, 29));
        stackedWidget->addWidget(Menue_1);
        Dep_Money = new QWidget();
        Dep_Money->setObjectName(QString::fromUtf8("Dep_Money"));
        groupBox_4 = new QGroupBox(Dep_Money);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(210, 140, 381, 341));
        groupBox_4->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_16 = new QToolButton(groupBox_4);
        toolButton_16->setObjectName(QString::fromUtf8("toolButton_16"));
        toolButton_16->setGeometry(QRect(30, 50, 131, 27));
        toolButton_18 = new QToolButton(groupBox_4);
        toolButton_18->setObjectName(QString::fromUtf8("toolButton_18"));
        toolButton_18->setGeometry(QRect(30, 130, 131, 27));
        pushButton_19 = new QPushButton(groupBox_4);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(240, 230, 83, 29));
        pushButton_48 = new QPushButton(groupBox_4);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(30, 230, 83, 29));
        label = new QLabel(groupBox_4);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(170, 50, 151, 31));
        lineEdit_10 = new QLineEdit(groupBox_4);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(170, 130, 161, 28));
        toolButton_12 = new QToolButton(groupBox_4);
        toolButton_12->setObjectName(QString::fromUtf8("toolButton_12"));
        toolButton_12->setGeometry(QRect(30, 90, 131, 31));
        lineEdit = new QLineEdit(groupBox_4);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(170, 90, 161, 31));
        stackedWidget->addWidget(Dep_Money);
        With_Money = new QWidget();
        With_Money->setObjectName(QString::fromUtf8("With_Money"));
        groupBox_5 = new QGroupBox(With_Money);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(220, 80, 531, 441));
        groupBox_5->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_22 = new QToolButton(groupBox_5);
        toolButton_22->setObjectName(QString::fromUtf8("toolButton_22"));
        toolButton_22->setGeometry(QRect(80, 70, 141, 27));
        toolButton_24 = new QToolButton(groupBox_5);
        toolButton_24->setObjectName(QString::fromUtf8("toolButton_24"));
        toolButton_24->setGeometry(QRect(80, 180, 141, 27));
        pushButton_21 = new QPushButton(groupBox_5);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(320, 270, 83, 29));
        pushButton_49 = new QPushButton(groupBox_5);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(80, 270, 83, 29));
        label_3 = new QLabel(groupBox_5);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(270, 70, 131, 21));
        lineEdit_11 = new QLineEdit(groupBox_5);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(270, 180, 131, 28));
        pushButton_60 = new QPushButton(groupBox_5);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(80, 120, 141, 31));
        lineEdit_2 = new QLineEdit(groupBox_5);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(270, 120, 131, 31));
        stackedWidget->addWidget(With_Money);
        Loan_1st = new QWidget();
        Loan_1st->setObjectName(QString::fromUtf8("Loan_1st"));
        groupBox_6 = new QGroupBox(Loan_1st);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(130, 60, 611, 401));
        groupBox_6->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_28 = new QToolButton(groupBox_6);
        toolButton_28->setObjectName(QString::fromUtf8("toolButton_28"));
        toolButton_28->setGeometry(QRect(10, 50, 571, 27));
        toolButton_29 = new QToolButton(groupBox_6);
        toolButton_29->setObjectName(QString::fromUtf8("toolButton_29"));
        toolButton_29->setGeometry(QRect(10, 90, 571, 27));
        toolButton_30 = new QToolButton(groupBox_6);
        toolButton_30->setObjectName(QString::fromUtf8("toolButton_30"));
        toolButton_30->setGeometry(QRect(10, 130, 571, 27));
        pushButton_23 = new QPushButton(groupBox_6);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(510, 360, 83, 29));
        pushButton_50 = new QPushButton(groupBox_6);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(10, 360, 83, 29));
        stackedWidget->addWidget(Loan_1st);
        Loan_Form = new QWidget();
        Loan_Form->setObjectName(QString::fromUtf8("Loan_Form"));
        groupBox_7 = new QGroupBox(Loan_Form);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(180, 60, 451, 421));
        groupBox_7->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_31 = new QToolButton(groupBox_7);
        toolButton_31->setObjectName(QString::fromUtf8("toolButton_31"));
        toolButton_31->setGeometry(QRect(50, 40, 181, 27));
        toolButton_31->setStyleSheet(QString::fromUtf8(""));
        toolButton_32 = new QToolButton(groupBox_7);
        toolButton_32->setObjectName(QString::fromUtf8("toolButton_32"));
        toolButton_32->setGeometry(QRect(50, 70, 181, 27));
        toolButton_33 = new QToolButton(groupBox_7);
        toolButton_33->setObjectName(QString::fromUtf8("toolButton_33"));
        toolButton_33->setGeometry(QRect(50, 100, 181, 27));
        pushButton_24 = new QPushButton(groupBox_7);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(310, 340, 83, 29));
        pushButton_51 = new QPushButton(groupBox_7);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(60, 340, 83, 29));
        lineEdit_12 = new QLineEdit(groupBox_7);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(240, 40, 191, 28));
        lineEdit_13 = new QLineEdit(groupBox_7);
        lineEdit_13->setObjectName(QString::fromUtf8("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(240, 70, 191, 28));
        lineEdit_14 = new QLineEdit(groupBox_7);
        lineEdit_14->setObjectName(QString::fromUtf8("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(240, 100, 191, 28));
        stackedWidget->addWidget(Loan_Form);
        pagee12 = new QWidget();
        pagee12->setObjectName(QString::fromUtf8("pagee12"));
        toolButton_37 = new QToolButton(pagee12);
        toolButton_37->setObjectName(QString::fromUtf8("toolButton_37"));
        toolButton_37->setGeometry(QRect(50, 160, 741, 141));
        toolButton_37->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_25 = new QPushButton(pagee12);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(690, 410, 83, 29));
        stackedWidget->addWidget(pagee12);
        pagee13 = new QWidget();
        pagee13->setObjectName(QString::fromUtf8("pagee13"));
        toolButton_38 = new QToolButton(pagee13);
        toolButton_38->setObjectName(QString::fromUtf8("toolButton_38"));
        toolButton_38->setGeometry(QRect(100, 60, 641, 181));
        toolButton_38->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_26 = new QPushButton(pagee13);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(660, 400, 83, 29));
        pushButton_52 = new QPushButton(pagee13);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(90, 400, 83, 29));
        stackedWidget->addWidget(pagee13);
        Fdr = new QWidget();
        Fdr->setObjectName(QString::fromUtf8("Fdr"));
        groupBox_8 = new QGroupBox(Fdr);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(220, 150, 371, 341));
        groupBox_8->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_39 = new QToolButton(groupBox_8);
        toolButton_39->setObjectName(QString::fromUtf8("toolButton_39"));
        toolButton_39->setGeometry(QRect(0, 90, 131, 27));
        pushButton_27 = new QPushButton(groupBox_8);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(280, 160, 83, 29));
        pushButton_53 = new QPushButton(groupBox_8);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(0, 160, 83, 29));
        lineEdit_15 = new QLineEdit(groupBox_8);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(160, 90, 191, 28));
        stackedWidget->addWidget(Fdr);
        pagee15 = new QWidget();
        pagee15->setObjectName(QString::fromUtf8("pagee15"));
        toolButton_50 = new QToolButton(pagee15);
        toolButton_50->setObjectName(QString::fromUtf8("toolButton_50"));
        toolButton_50->setGeometry(QRect(210, 140, 401, 27));
        toolButton_50->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_34 = new QPushButton(pagee15);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(620, 320, 83, 29));
        stackedWidget->addWidget(pagee15);
        Pay_Bill = new QWidget();
        Pay_Bill->setObjectName(QString::fromUtf8("Pay_Bill"));
        groupBox_9 = new QGroupBox(Pay_Bill);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(140, 110, 521, 311));
        groupBox_9->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_41 = new QToolButton(groupBox_9);
        toolButton_41->setObjectName(QString::fromUtf8("toolButton_41"));
        toolButton_41->setGeometry(QRect(0, 90, 241, 27));
        toolButton_43 = new QToolButton(groupBox_9);
        toolButton_43->setObjectName(QString::fromUtf8("toolButton_43"));
        toolButton_43->setGeometry(QRect(0, 130, 241, 27));
        Pay_Bill_2 = new QPushButton(groupBox_9);
        Pay_Bill_2->setObjectName(QString::fromUtf8("Pay_Bill_2"));
        Pay_Bill_2->setGeometry(QRect(440, 280, 83, 29));
        pushButton_54 = new QPushButton(groupBox_9);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(0, 280, 83, 29));
        lineEdit_16 = new QLineEdit(groupBox_9);
        lineEdit_16->setObjectName(QString::fromUtf8("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(260, 90, 231, 28));
        lineEdit_17 = new QLineEdit(groupBox_9);
        lineEdit_17->setObjectName(QString::fromUtf8("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(260, 130, 231, 28));
        pushButton_28 = new QPushButton(groupBox_9);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(0, 50, 241, 31));
        lineEdit_3 = new QLineEdit(groupBox_9);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(260, 50, 231, 31));
        stackedWidget->addWidget(Pay_Bill);
        pagee17 = new QWidget();
        pagee17->setObjectName(QString::fromUtf8("pagee17"));
        toolButton_51 = new QToolButton(pagee17);
        toolButton_51->setObjectName(QString::fromUtf8("toolButton_51"));
        toolButton_51->setGeometry(QRect(130, 150, 541, 27));
        toolButton_51->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_35 = new QPushButton(pagee17);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(340, 300, 83, 29));
        stackedWidget->addWidget(pagee17);
        MBY = new QWidget();
        MBY->setObjectName(QString::fromUtf8("MBY"));
        pushButton_29 = new QPushButton(MBY);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(270, 60, 221, 29));
        pushButton_30 = new QPushButton(MBY);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(270, 110, 221, 29));
        pushButton_31 = new QPushButton(MBY);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(270, 160, 221, 29));
        pushButton_55 = new QPushButton(MBY);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(340, 230, 83, 29));
        stackedWidget->addWidget(MBY);
        pagee19 = new QWidget();
        pagee19->setObjectName(QString::fromUtf8("pagee19"));
        groupBox_10 = new QGroupBox(pagee19);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(210, 90, 461, 461));
        groupBox_10->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_45 = new QToolButton(groupBox_10);
        toolButton_45->setObjectName(QString::fromUtf8("toolButton_45"));
        toolButton_45->setGeometry(QRect(50, 20, 321, 41));
        toolButton_46 = new QToolButton(groupBox_10);
        toolButton_46->setObjectName(QString::fromUtf8("toolButton_46"));
        toolButton_46->setGeometry(QRect(50, 60, 321, 41));
        toolButton_47 = new QToolButton(groupBox_10);
        toolButton_47->setObjectName(QString::fromUtf8("toolButton_47"));
        toolButton_47->setGeometry(QRect(50, 100, 321, 51));
        toolButton_48 = new QToolButton(groupBox_10);
        toolButton_48->setObjectName(QString::fromUtf8("toolButton_48"));
        toolButton_48->setGeometry(QRect(50, 150, 321, 51));
        pushButton_56 = new QPushButton(groupBox_10);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(180, 210, 83, 29));
        stackedWidget->addWidget(pagee19);
        pageee20 = new QWidget();
        pageee20->setObjectName(QString::fromUtf8("pageee20"));
        toolButton_49 = new QToolButton(pageee20);
        toolButton_49->setObjectName(QString::fromUtf8("toolButton_49"));
        toolButton_49->setGeometry(QRect(30, 30, 751, 51));
        toolButton_49->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_52 = new QToolButton(pageee20);
        toolButton_52->setObjectName(QString::fromUtf8("toolButton_52"));
        toolButton_52->setGeometry(QRect(30, 80, 751, 51));
        toolButton_52->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_53 = new QToolButton(pageee20);
        toolButton_53->setObjectName(QString::fromUtf8("toolButton_53"));
        toolButton_53->setGeometry(QRect(30, 130, 751, 51));
        toolButton_53->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_36 = new QPushButton(pageee20);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(690, 320, 83, 29));
        pushButton_58 = new QPushButton(pageee20);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(60, 320, 83, 29));
        stackedWidget->addWidget(pageee20);
        Yearly_Report = new QWidget();
        Yearly_Report->setObjectName(QString::fromUtf8("Yearly_Report"));
        groupBox_11 = new QGroupBox(Yearly_Report);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(170, 110, 511, 381));
        groupBox_11->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_54 = new QToolButton(groupBox_11);
        toolButton_54->setObjectName(QString::fromUtf8("toolButton_54"));
        toolButton_54->setGeometry(QRect(30, 20, 451, 27));
        toolButton_55 = new QToolButton(groupBox_11);
        toolButton_55->setObjectName(QString::fromUtf8("toolButton_55"));
        toolButton_55->setGeometry(QRect(30, 60, 201, 27));
        toolButton_56 = new QToolButton(groupBox_11);
        toolButton_56->setObjectName(QString::fromUtf8("toolButton_56"));
        toolButton_56->setGeometry(QRect(240, 60, 241, 27));
        toolButton_57 = new QToolButton(groupBox_11);
        toolButton_57->setObjectName(QString::fromUtf8("toolButton_57"));
        toolButton_57->setGeometry(QRect(30, 90, 201, 27));
        toolButton_58 = new QToolButton(groupBox_11);
        toolButton_58->setObjectName(QString::fromUtf8("toolButton_58"));
        toolButton_58->setGeometry(QRect(240, 90, 241, 27));
        toolButton_59 = new QToolButton(groupBox_11);
        toolButton_59->setObjectName(QString::fromUtf8("toolButton_59"));
        toolButton_59->setGeometry(QRect(30, 120, 201, 27));
        toolButton_60 = new QToolButton(groupBox_11);
        toolButton_60->setObjectName(QString::fromUtf8("toolButton_60"));
        toolButton_60->setGeometry(QRect(240, 120, 241, 27));
        toolButton_61 = new QToolButton(groupBox_11);
        toolButton_61->setObjectName(QString::fromUtf8("toolButton_61"));
        toolButton_61->setGeometry(QRect(30, 150, 201, 27));
        toolButton_62 = new QToolButton(groupBox_11);
        toolButton_62->setObjectName(QString::fromUtf8("toolButton_62"));
        toolButton_62->setGeometry(QRect(240, 150, 241, 27));
        toolButton_63 = new QToolButton(groupBox_11);
        toolButton_63->setObjectName(QString::fromUtf8("toolButton_63"));
        toolButton_63->setGeometry(QRect(30, 180, 201, 27));
        toolButton_64 = new QToolButton(groupBox_11);
        toolButton_64->setObjectName(QString::fromUtf8("toolButton_64"));
        toolButton_64->setGeometry(QRect(240, 180, 241, 27));
        pushButton_37 = new QPushButton(groupBox_11);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(200, 240, 83, 29));
        stackedWidget->addWidget(Yearly_Report);
        Bank_Details = new QWidget();
        Bank_Details->setObjectName(QString::fromUtf8("Bank_Details"));
        toolButton_65 = new QToolButton(Bank_Details);
        toolButton_65->setObjectName(QString::fromUtf8("toolButton_65"));
        toolButton_65->setGeometry(QRect(10, 30, 771, 31));
        toolButton_66 = new QToolButton(Bank_Details);
        toolButton_66->setObjectName(QString::fromUtf8("toolButton_66"));
        toolButton_66->setGeometry(QRect(10, 60, 771, 27));
        toolButton_67 = new QToolButton(Bank_Details);
        toolButton_67->setObjectName(QString::fromUtf8("toolButton_67"));
        toolButton_67->setGeometry(QRect(10, 90, 771, 27));
        toolButton_68 = new QToolButton(Bank_Details);
        toolButton_68->setObjectName(QString::fromUtf8("toolButton_68"));
        toolButton_68->setGeometry(QRect(10, 120, 771, 27));
        toolButton_69 = new QToolButton(Bank_Details);
        toolButton_69->setObjectName(QString::fromUtf8("toolButton_69"));
        toolButton_69->setGeometry(QRect(10, 150, 771, 27));
        pushButton_38 = new QPushButton(Bank_Details);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(670, 200, 83, 29));
        stackedWidget->addWidget(Bank_Details);
        Branch = new QWidget();
        Branch->setObjectName(QString::fromUtf8("Branch"));
        toolButton_70 = new QToolButton(Branch);
        toolButton_70->setObjectName(QString::fromUtf8("toolButton_70"));
        toolButton_70->setGeometry(QRect(130, 110, 571, 27));
        toolButton_71 = new QToolButton(Branch);
        toolButton_71->setObjectName(QString::fromUtf8("toolButton_71"));
        toolButton_71->setGeometry(QRect(130, 160, 571, 27));
        pushButton_39 = new QPushButton(Branch);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(330, 210, 83, 29));
        stackedWidget->addWidget(Branch);
        Announcement = new QWidget();
        Announcement->setObjectName(QString::fromUtf8("Announcement"));
        groupBox_14 = new QGroupBox(Announcement);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(260, 90, 301, 271));
        groupBox_14->setStyleSheet(QString::fromUtf8("Border:none;"));
        pushButton_41 = new QPushButton(groupBox_14);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(80, 70, 121, 29));
        pushButton_59 = new QPushButton(groupBox_14);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(100, 170, 83, 29));
        pushButton_40 = new QPushButton(groupBox_14);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(80, 120, 121, 29));
        stackedWidget->addWidget(Announcement);
        Vacation = new QWidget();
        Vacation->setObjectName(QString::fromUtf8("Vacation"));
        groupBox_12 = new QGroupBox(Vacation);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(10, 0, 771, 551));
        groupBox_12->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_73 = new QToolButton(groupBox_12);
        toolButton_73->setObjectName(QString::fromUtf8("toolButton_73"));
        toolButton_73->setGeometry(QRect(0, 20, 411, 27));
        toolButton_74 = new QToolButton(groupBox_12);
        toolButton_74->setObjectName(QString::fromUtf8("toolButton_74"));
        toolButton_74->setGeometry(QRect(0, 50, 411, 27));
        toolButton_75 = new QToolButton(groupBox_12);
        toolButton_75->setObjectName(QString::fromUtf8("toolButton_75"));
        toolButton_75->setGeometry(QRect(0, 80, 411, 27));
        toolButton_76 = new QToolButton(groupBox_12);
        toolButton_76->setObjectName(QString::fromUtf8("toolButton_76"));
        toolButton_76->setGeometry(QRect(0, 110, 411, 27));
        toolButton_77 = new QToolButton(groupBox_12);
        toolButton_77->setObjectName(QString::fromUtf8("toolButton_77"));
        toolButton_77->setGeometry(QRect(0, 140, 411, 27));
        toolButton_78 = new QToolButton(groupBox_12);
        toolButton_78->setObjectName(QString::fromUtf8("toolButton_78"));
        toolButton_78->setGeometry(QRect(0, 170, 411, 27));
        toolButton_79 = new QToolButton(groupBox_12);
        toolButton_79->setObjectName(QString::fromUtf8("toolButton_79"));
        toolButton_79->setGeometry(QRect(0, 200, 411, 27));
        toolButton_80 = new QToolButton(groupBox_12);
        toolButton_80->setObjectName(QString::fromUtf8("toolButton_80"));
        toolButton_80->setGeometry(QRect(0, 230, 411, 27));
        toolButton_81 = new QToolButton(groupBox_12);
        toolButton_81->setObjectName(QString::fromUtf8("toolButton_81"));
        toolButton_81->setGeometry(QRect(0, 260, 411, 27));
        toolButton_82 = new QToolButton(groupBox_12);
        toolButton_82->setObjectName(QString::fromUtf8("toolButton_82"));
        toolButton_82->setGeometry(QRect(0, 290, 411, 27));
        toolButton_83 = new QToolButton(groupBox_12);
        toolButton_83->setObjectName(QString::fromUtf8("toolButton_83"));
        toolButton_83->setGeometry(QRect(0, 320, 411, 27));
        toolButton_84 = new QToolButton(groupBox_12);
        toolButton_84->setObjectName(QString::fromUtf8("toolButton_84"));
        toolButton_84->setGeometry(QRect(0, 350, 411, 27));
        toolButton_85 = new QToolButton(groupBox_12);
        toolButton_85->setObjectName(QString::fromUtf8("toolButton_85"));
        toolButton_85->setGeometry(QRect(0, 380, 411, 27));
        toolButton_86 = new QToolButton(groupBox_12);
        toolButton_86->setObjectName(QString::fromUtf8("toolButton_86"));
        toolButton_86->setGeometry(QRect(0, 410, 411, 27));
        toolButton_87 = new QToolButton(groupBox_12);
        toolButton_87->setObjectName(QString::fromUtf8("toolButton_87"));
        toolButton_87->setGeometry(QRect(0, 440, 411, 27));
        toolButton_88 = new QToolButton(groupBox_12);
        toolButton_88->setObjectName(QString::fromUtf8("toolButton_88"));
        toolButton_88->setGeometry(QRect(0, 470, 411, 27));
        toolButton_89 = new QToolButton(groupBox_12);
        toolButton_89->setObjectName(QString::fromUtf8("toolButton_89"));
        toolButton_89->setGeometry(QRect(420, 20, 341, 27));
        toolButton_90 = new QToolButton(groupBox_12);
        toolButton_90->setObjectName(QString::fromUtf8("toolButton_90"));
        toolButton_90->setGeometry(QRect(420, 50, 341, 27));
        toolButton_91 = new QToolButton(groupBox_12);
        toolButton_91->setObjectName(QString::fromUtf8("toolButton_91"));
        toolButton_91->setGeometry(QRect(420, 80, 341, 27));
        toolButton_92 = new QToolButton(groupBox_12);
        toolButton_92->setObjectName(QString::fromUtf8("toolButton_92"));
        toolButton_92->setGeometry(QRect(420, 110, 341, 27));
        toolButton_93 = new QToolButton(groupBox_12);
        toolButton_93->setObjectName(QString::fromUtf8("toolButton_93"));
        toolButton_93->setGeometry(QRect(420, 140, 341, 27));
        toolButton_94 = new QToolButton(groupBox_12);
        toolButton_94->setObjectName(QString::fromUtf8("toolButton_94"));
        toolButton_94->setGeometry(QRect(420, 170, 341, 27));
        toolButton_95 = new QToolButton(groupBox_12);
        toolButton_95->setObjectName(QString::fromUtf8("toolButton_95"));
        toolButton_95->setGeometry(QRect(420, 200, 341, 27));
        toolButton_96 = new QToolButton(groupBox_12);
        toolButton_96->setObjectName(QString::fromUtf8("toolButton_96"));
        toolButton_96->setGeometry(QRect(420, 230, 341, 27));
        toolButton_97 = new QToolButton(groupBox_12);
        toolButton_97->setObjectName(QString::fromUtf8("toolButton_97"));
        toolButton_97->setGeometry(QRect(420, 260, 341, 27));
        toolButton_98 = new QToolButton(groupBox_12);
        toolButton_98->setObjectName(QString::fromUtf8("toolButton_98"));
        toolButton_98->setGeometry(QRect(420, 290, 341, 27));
        toolButton_99 = new QToolButton(groupBox_12);
        toolButton_99->setObjectName(QString::fromUtf8("toolButton_99"));
        toolButton_99->setGeometry(QRect(420, 320, 341, 27));
        toolButton_100 = new QToolButton(groupBox_12);
        toolButton_100->setObjectName(QString::fromUtf8("toolButton_100"));
        toolButton_100->setGeometry(QRect(420, 350, 341, 27));
        toolButton_101 = new QToolButton(groupBox_12);
        toolButton_101->setObjectName(QString::fromUtf8("toolButton_101"));
        toolButton_101->setGeometry(QRect(420, 380, 341, 27));
        toolButton_102 = new QToolButton(groupBox_12);
        toolButton_102->setObjectName(QString::fromUtf8("toolButton_102"));
        toolButton_102->setGeometry(QRect(420, 410, 341, 27));
        toolButton_103 = new QToolButton(groupBox_12);
        toolButton_103->setObjectName(QString::fromUtf8("toolButton_103"));
        toolButton_103->setGeometry(QRect(420, 440, 341, 27));
        toolButton_104 = new QToolButton(groupBox_12);
        toolButton_104->setObjectName(QString::fromUtf8("toolButton_104"));
        toolButton_104->setGeometry(QRect(420, 470, 341, 27));
        pushButton_43 = new QPushButton(groupBox_12);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(680, 520, 83, 29));
        toolButton_105 = new QToolButton(groupBox_12);
        toolButton_105->setObjectName(QString::fromUtf8("toolButton_105"));
        toolButton_105->setGeometry(QRect(270, 520, 351, 27));
        stackedWidget->addWidget(Vacation);
        Reqrutement_Notice = new QWidget();
        Reqrutement_Notice->setObjectName(QString::fromUtf8("Reqrutement_Notice"));
        groupBox_13 = new QGroupBox(Reqrutement_Notice);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(50, 30, 741, 251));
        groupBox_13->setStyleSheet(QString::fromUtf8("Border:none;"));
        toolButton_106 = new QToolButton(groupBox_13);
        toolButton_106->setObjectName(QString::fromUtf8("toolButton_106"));
        toolButton_106->setGeometry(QRect(40, 110, 661, 27));
        pushButton_44 = new QPushButton(Reqrutement_Notice);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(680, 320, 83, 29));
        stackedWidget->addWidget(Reqrutement_Notice);
        pageee28 = new QWidget();
        pageee28->setObjectName(QString::fromUtf8("pageee28"));
        toolButton_107 = new QToolButton(pageee28);
        toolButton_107->setObjectName(QString::fromUtf8("toolButton_107"));
        toolButton_107->setGeometry(QRect(70, 80, 731, 201));
        toolButton_107->setStyleSheet(QString::fromUtf8("font: 16pt \"MS Shell Dlg 2\";\n"
"Border:none;"));
        pushButton_20 = new QPushButton(pageee28);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(370, 350, 83, 29));
        stackedWidget->addWidget(pageee28);
        pageee29 = new QWidget();
        pageee29->setObjectName(QString::fromUtf8("pageee29"));
        lineEdit_8 = new QLineEdit(pageee29);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(240, 200, 331, 28));
        pushButton_22 = new QPushButton(pageee29);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(650, 320, 83, 29));
        stackedWidget->addWidget(pageee29);
        pageee30 = new QWidget();
        pageee30->setObjectName(QString::fromUtf8("pageee30"));
        lineEdit_9 = new QLineEdit(pageee30);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(260, 170, 331, 28));
        pushButton_57 = new QPushButton(pageee30);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(670, 310, 83, 29));
        stackedWidget->addWidget(pageee30);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        lineEdit_4 = new QLineEdit(page);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(90, 40, 113, 20));
        lineEdit_18 = new QLineEdit(page);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(90, 70, 113, 20));
        lineEdit_19 = new QLineEdit(page);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(230, 40, 113, 20));
        lineEdit_20 = new QLineEdit(page);
        lineEdit_20->setObjectName(QString::fromUtf8("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(230, 70, 113, 20));
        pushButton_61 = new QPushButton(page);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(280, 110, 75, 23));
        stackedWidget->addWidget(page);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 800, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        toolButton->setText(QApplication::translate("MainWindow", "Trust Bank", nullptr));
        toolButton_2->setText(QApplication::translate("MainWindow", "Secured your money.", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_3->setText(QApplication::translate("MainWindow", "Aim", nullptr));
        toolButton_4->setText(QApplication::translate("MainWindow", "To secure peoople's money.", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_32->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Register", nullptr));
        pushButton_9->setText(QApplication::translate("MainWindow", "Log In", nullptr));
        pushButton_33->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox->setTitle(QString());
        toolButton_5->setText(QApplication::translate("MainWindow", "Name", nullptr));
        toolButton_6->setText(QApplication::translate("MainWindow", "Mail", nullptr));
        toolButton_7->setText(QApplication::translate("MainWindow", "Phone Number", nullptr));
        toolButton_8->setText(QApplication::translate("MainWindow", "Password", nullptr));
        pushButton_10->setText(QApplication::translate("MainWindow", "Register", nullptr));
        pushButton_45->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_2->setTitle(QString());
        toolButton_9->setText(QApplication::translate("MainWindow", "Name", nullptr));
        toolButton_10->setText(QApplication::translate("MainWindow", "Email", nullptr));
        toolButton_11->setText(QApplication::translate("MainWindow", "Password", nullptr));
        pushButton_11->setText(QApplication::translate("MainWindow", "Log in", nullptr));
        pushButton_46->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_3->setTitle(QString());
        pushButton_12->setText(QApplication::translate("MainWindow", "Deposit", nullptr));
        pushButton_13->setText(QApplication::translate("MainWindow", "Withdraw", nullptr));
        pushButton_14->setText(QApplication::translate("MainWindow", "Loan", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "Fixed Deposit", nullptr));
        pushButton_16->setText(QApplication::translate("MainWindow", "Pay-Bill", nullptr));
        pushButton_17->setText(QApplication::translate("MainWindow", "Exit", nullptr));
        education->setText(QApplication::translate("MainWindow", "Education Loan", nullptr));
        toolButton_15->setText(QApplication::translate("MainWindow", "Congratulations!You have register your account successfully.Thank You.", nullptr));
        pushButton_18->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "My Profile", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Authority", nullptr));
        pushButton_5->setText(QApplication::translate("MainWindow", "Bank Details", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Branches", nullptr));
        pushButton_7->setText(QApplication::translate("MainWindow", "Announcement", nullptr));
        pushButton_47->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_42->setText(QApplication::translate("MainWindow", "Exit", nullptr));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Deposite money", nullptr));
        toolButton_16->setText(QApplication::translate("MainWindow", "My Deposit", nullptr));
        toolButton_18->setText(QApplication::translate("MainWindow", "Deposit money", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "Confirm", nullptr));
        pushButton_48->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label->setText(QString());
        toolButton_12->setText(QApplication::translate("MainWindow", "Email", nullptr));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Withdraw", nullptr));
        toolButton_22->setText(QApplication::translate("MainWindow", "Current Money", nullptr));
        toolButton_24->setText(QApplication::translate("MainWindow", "Withdraw Money", nullptr));
        pushButton_21->setText(QApplication::translate("MainWindow", "Confrim", nullptr));
        pushButton_49->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label_3->setText(QString());
        pushButton_60->setText(QApplication::translate("MainWindow", "Email", nullptr));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Dear sir/madam.Assalamu alaikum Warahmatullah.", nullptr));
        toolButton_28->setText(QApplication::translate("MainWindow", "You can take loan from 10,000-200,000 with 3% interest rate", nullptr));
        toolButton_29->setText(QApplication::translate("MainWindow", "You can take loan from 200,001-500,000- with 5% interest rate", nullptr));
        toolButton_30->setText(QApplication::translate("MainWindow", "You can take loan from 500,001-700,000-- with 8% interest rate", nullptr));
        pushButton_23->setText(QApplication::translate("MainWindow", "I Agree", nullptr));
        pushButton_50->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Loan form", nullptr));
        toolButton_31->setText(QApplication::translate("MainWindow", "Purpose", nullptr));
        toolButton_32->setText(QApplication::translate("MainWindow", "Enter ammount", nullptr));
        toolButton_33->setText(QApplication::translate("MainWindow", "How long will it take you", nullptr));
        pushButton_24->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_51->setText(QApplication::translate("MainWindow", "Back", nullptr));
        toolButton_37->setText(QApplication::translate("MainWindow", "Congratulations! you have got the  loan successfully!!", nullptr));
        pushButton_25->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_38->setText(QApplication::translate("MainWindow", "You can  deposit for a certain  time,we will give you 6% interest in your money. ", nullptr));
        pushButton_26->setText(QApplication::translate("MainWindow", "I agree", nullptr));
        pushButton_52->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Fixed Deposit", nullptr));
        toolButton_39->setText(QApplication::translate("MainWindow", "Enter Ammount", nullptr));
        pushButton_27->setText(QApplication::translate("MainWindow", "Confrim", nullptr));
        pushButton_53->setText(QApplication::translate("MainWindow", "Back", nullptr));
        toolButton_50->setText(QApplication::translate("MainWindow", "Congratulations! Your fixed deposite has been confirmed", nullptr));
        pushButton_34->setText(QApplication::translate("MainWindow", "Next", nullptr));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Pay Your Utilyty Bill", nullptr));
        toolButton_41->setText(QApplication::translate("MainWindow", "Enter Your ID", nullptr));
        toolButton_43->setText(QApplication::translate("MainWindow", "Enter Ammount", nullptr));
        Pay_Bill_2->setText(QApplication::translate("MainWindow", "Confirm", nullptr));
        pushButton_54->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_28->setText(QApplication::translate("MainWindow", "Email", nullptr));
        toolButton_51->setText(QApplication::translate("MainWindow", "Successfully you have paid your utility bill", nullptr));
        pushButton_35->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_29->setText(QApplication::translate("MainWindow", "Managing Body", nullptr));
        pushButton_30->setText(QApplication::translate("MainWindow", "Bank Hostory", nullptr));
        pushButton_31->setText(QApplication::translate("MainWindow", "Yearly  Report", nullptr));
        pushButton_55->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Managing Body", nullptr));
        toolButton_45->setText(QApplication::translate("MainWindow", "Managing director", nullptr));
        toolButton_46->setText(QApplication::translate("MainWindow", "Md.Mohiuddin ", nullptr));
        toolButton_47->setText(QApplication::translate("MainWindow", "CEO", nullptr));
        toolButton_48->setText(QApplication::translate("MainWindow", "A.K.M. Afjal ", nullptr));
        pushButton_56->setText(QApplication::translate("MainWindow", "Back", nullptr));
        toolButton_49->setText(QApplication::translate("MainWindow", "Trust  Bank was established on 31 December 1981. This was the first joint venture private bank in Bangladesh... ", nullptr));
        toolButton_52->setText(QApplication::translate("MainWindow", "With an ambition to secure its place as the leading service provider, creating lasting value for its clientele  and", nullptr));
        toolButton_53->setText(QApplication::translate("MainWindow", "and employees and particularly for the community it operates in,", nullptr));
        pushButton_36->setText(QApplication::translate("MainWindow", "Next", nullptr));
        pushButton_58->setText(QApplication::translate("MainWindow", "Back", nullptr));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "Yearly Report", nullptr));
        toolButton_54->setText(QApplication::translate("MainWindow", "session 22-23", nullptr));
        toolButton_55->setText(QApplication::translate("MainWindow", "number of savings annount", nullptr));
        toolButton_56->setText(QApplication::translate("MainWindow", "15390", nullptr));
        toolButton_57->setText(QApplication::translate("MainWindow", "number of CC account", nullptr));
        toolButton_58->setText(QApplication::translate("MainWindow", "850", nullptr));
        toolButton_59->setText(QApplication::translate("MainWindow", "Given loan", nullptr));
        toolButton_60->setText(QApplication::translate("MainWindow", "15core", nullptr));
        toolButton_61->setText(QApplication::translate("MainWindow", "New property", nullptr));
        toolButton_62->setText(QApplication::translate("MainWindow", "own 2 plot in Dhaka city", nullptr));
        toolButton_63->setText(QApplication::translate("MainWindow", "total Yearlt revinue", nullptr));
        toolButton_64->setText(QApplication::translate("MainWindow", "4 thousand core", nullptr));
        pushButton_37->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_65->setText(QApplication::translate("MainWindow", "Trust Bank was established on 31 December 1981.[3] [4] This was the first joint venture private bank in Bangladesh. ", nullptr));
        toolButton_66->setText(QApplication::translate("MainWindow", " On 14 November 2007 Bangladesh bank approved the name trust Bank.A former deputy managing director was ", nullptr));
        toolButton_67->setText(QApplication::translate("MainWindow", "charged with embezzling 3.25 billion taka from the bank.In February 2008, Trust Bank was fined 100 million taka for ", nullptr));
        toolButton_68->setText(QApplication::translate("MainWindow", "violating securities law with excessive marginal loans.The majority of these loans from the merchant banking wings", nullptr));
        toolButton_69->setText(QApplication::translate("MainWindow", "of Trust Bank went to bank employees and their relatives...", nullptr));
        pushButton_38->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_70->setText(QApplication::translate("MainWindow", "We will input our all information obout our all branches of the whole Bangladesh", nullptr));
        toolButton_71->setText(QApplication::translate("MainWindow", "Stay connected with us", nullptr));
        pushButton_39->setText(QApplication::translate("MainWindow", "Next", nullptr));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "Announcement", nullptr));
        pushButton_41->setText(QApplication::translate("MainWindow", "Vacation", nullptr));
        pushButton_59->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_40->setText(QApplication::translate("MainWindow", "Recruitement", nullptr));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "list of vacation", nullptr));
        toolButton_73->setText(QApplication::translate("MainWindow", "Shaheed Day and International Mother Language Day", nullptr));
        toolButton_74->setText(QApplication::translate("MainWindow", "*Shab-e-Barat", nullptr));
        toolButton_75->setText(QApplication::translate("MainWindow", "Independence and National Day", nullptr));
        toolButton_76->setText(QApplication::translate("MainWindow", "Bengali New Year's Day", nullptr));
        toolButton_77->setText(QApplication::translate("MainWindow", "*Shab-e-Qadar", nullptr));
        toolButton_78->setText(QApplication::translate("MainWindow", "* Jumatul Wida", nullptr));
        toolButton_79->setText(QApplication::translate("MainWindow", "*Eid-ul-Fitr", nullptr));
        toolButton_80->setText(QApplication::translate("MainWindow", "May Day", nullptr));
        toolButton_81->setText(QApplication::translate("MainWindow", "*Buddha Purnima (Boishakhi Purnima)	", nullptr));
        toolButton_82->setText(QApplication::translate("MainWindow", "*Eid-ul-Azha", nullptr));
        toolButton_83->setText(QApplication::translate("MainWindow", "Bank Holiday", nullptr));
        toolButton_84->setText(QApplication::translate("MainWindow", "*Moharrum (Ashura)", nullptr));
        toolButton_85->setText(QApplication::translate("MainWindow", "National Mourning Day", nullptr));
        toolButton_86->setText(QApplication::translate("MainWindow", "*Janmashtami", nullptr));
        toolButton_87->setText(QApplication::translate("MainWindow", "*Eid-e-Miladun-Nabi (S)", nullptr));
        toolButton_88->setText(QApplication::translate("MainWindow", "Durga Puja (Bijoya Dashami)", nullptr));
        toolButton_89->setText(QApplication::translate("MainWindow", "21 February, Tuesday", nullptr));
        toolButton_90->setText(QApplication::translate("MainWindow", "08 March, Wednesday", nullptr));
        toolButton_91->setText(QApplication::translate("MainWindow", "26 March,Sunday", nullptr));
        toolButton_92->setText(QApplication::translate("MainWindow", "	14 April, Friday", nullptr));
        toolButton_93->setText(QApplication::translate("MainWindow", "19 April, Wednesday", nullptr));
        toolButton_94->setText(QApplication::translate("MainWindow", "21 April, Friday", nullptr));
        toolButton_95->setText(QApplication::translate("MainWindow", "21, 22 & 23 April, Friday, Saturday & Sunday", nullptr));
        toolButton_96->setText(QApplication::translate("MainWindow", "01 May, Monday", nullptr));
        toolButton_97->setText(QApplication::translate("MainWindow", "04 May, Thursday", nullptr));
        toolButton_98->setText(QApplication::translate("MainWindow", "28, 29 & 30 June, Wednesday, Thursday & Friday", nullptr));
        toolButton_99->setText(QApplication::translate("MainWindow", "01 July, Saturday", nullptr));
        toolButton_100->setText(QApplication::translate("MainWindow", "	29 July, Saturday", nullptr));
        toolButton_101->setText(QApplication::translate("MainWindow", "15 August, Tuesday", nullptr));
        toolButton_102->setText(QApplication::translate("MainWindow", "06 September, Wednesday", nullptr));
        toolButton_103->setText(QApplication::translate("MainWindow", "28 September, Thursday", nullptr));
        toolButton_104->setText(QApplication::translate("MainWindow", "24 October, Tuesday", nullptr));
        pushButton_43->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_105->setText(QApplication::translate("MainWindow", "* Subject to the appearance of the Moon.", nullptr));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "Recruitment Notice", nullptr));
        toolButton_106->setText(QApplication::translate("MainWindow", "At this time there is no reqrutment,if we need people we will circular it in our website,thank you", nullptr));
        pushButton_44->setText(QApplication::translate("MainWindow", "Next", nullptr));
        toolButton_107->setText(QApplication::translate("MainWindow", "Thank you.", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "Close", nullptr));
        lineEdit_8->setText(QApplication::translate("MainWindow", "Successfully you have deposited your money.Thank you", nullptr));
        pushButton_22->setText(QApplication::translate("MainWindow", "Next", nullptr));
        lineEdit_9->setText(QApplication::translate("MainWindow", "Successfully you have withdraw your money.Thank you.", nullptr));
        pushButton_57->setText(QApplication::translate("MainWindow", "Next", nullptr));
        lineEdit_4->setText(QApplication::translate("MainWindow", "mounth", nullptr));
        lineEdit_18->setText(QApplication::translate("MainWindow", "taka", nullptr));
        pushButton_61->setText(QApplication::translate("MainWindow", "confirm", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
